# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddWordDialog_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 33, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.new_wordEdit = QtWidgets.QLineEdit(Dialog)
        self.new_wordEdit.setGeometry(QtCore.QRect(150, 40, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.new_wordEdit.setFont(font)
        self.new_wordEdit.setText("")
        self.new_wordEdit.setObjectName("new_wordEdit")
        self.add_button = QtWidgets.QPushButton(Dialog)
        self.add_button.setGeometry(QtCore.QRect(260, 102, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Окно ввода"))
        self.label.setText(_translate("Dialog", "Новое слово"))
        self.add_button.setText(_translate("Dialog", "Добавить"))
