# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CountWordsDialog_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(270, 150)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        Dialog.setFont(font)
        self.words_count_spinBox = QtWidgets.QSpinBox(Dialog)
        self.words_count_spinBox.setEnabled(True)
        self.words_count_spinBox.setGeometry(QtCore.QRect(20, 60, 241, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.words_count_spinBox.setFont(font)
        self.words_count_spinBox.setStyleSheet("")
        self.words_count_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.words_count_spinBox.setReadOnly(False)
        self.words_count_spinBox.setKeyboardTracking(False)
        self.words_count_spinBox.setMinimum(10)
        self.words_count_spinBox.setMaximum(30)
        self.words_count_spinBox.setSingleStep(5)
        self.words_count_spinBox.setProperty("value", 15)
        self.words_count_spinBox.setObjectName("words_count_spinBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ready_btn = QtWidgets.QPushButton(Dialog)
        self.ready_btn.setGeometry(QtCore.QRect(170, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.ready_btn.setFont(font)
        self.ready_btn.setStyleSheet("")
        self.ready_btn.setObjectName("ready_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Окно ввода"))
        self.label.setText(_translate("Dialog", "Введите количество слов для тренировки"))
        self.ready_btn.setText(_translate("Dialog", "Готово"))
