# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 210)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.training_btn = QtWidgets.QPushButton(self.centralwidget)
        self.training_btn.setGeometry(QtCore.QRect(80, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.training_btn.setFont(font)
        self.training_btn.setStyleSheet("")
        self.training_btn.setObjectName("training_btn")
        self.my_dictionary_btn = QtWidgets.QPushButton(self.centralwidget)
        self.my_dictionary_btn.setGeometry(QtCore.QRect(80, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.my_dictionary_btn.setFont(font)
        self.my_dictionary_btn.setStyleSheet("")
        self.my_dictionary_btn.setObjectName("my_dictionary_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ударения.exe"))
        self.label.setText(_translate("MainWindow", "Ударения"))
        self.training_btn.setText(_translate("MainWindow", "Тренировка"))
        self.my_dictionary_btn.setText(_translate("MainWindow", "Мой словарь"))
