# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyDictionaryDialog_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 120, 321, 192))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.search_word_Edit = QtWidgets.QLineEdit(Dialog)
        self.search_word_Edit.setGeometry(QtCore.QRect(20, 50, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.search_word_Edit.setFont(font)
        self.search_word_Edit.setObjectName("search_word_Edit")
        self.search_string_label = QtWidgets.QLabel(Dialog)
        self.search_string_label.setGeometry(QtCore.QRect(10, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.search_string_label.setFont(font)
        self.search_string_label.setAlignment(QtCore.Qt.AlignCenter)
        self.search_string_label.setObjectName("search_string_label")
        self.add_word_button = QtWidgets.QPushButton(Dialog)
        self.add_word_button.setGeometry(QtCore.QRect(130, 320, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.add_word_button.setFont(font)
        self.add_word_button.setObjectName("add_word_button")
        self.delete_word_button = QtWidgets.QPushButton(Dialog)
        self.delete_word_button.setEnabled(False)
        self.delete_word_button.setGeometry(QtCore.QRect(254, 320, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.delete_word_button.setFont(font)
        self.delete_word_button.setObjectName("delete_word_button")
        self.back_to_main_menu_button = QtWidgets.QPushButton(Dialog)
        self.back_to_main_menu_button.setGeometry(QtCore.QRect(30, 320, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.back_to_main_menu_button.setFont(font)
        self.back_to_main_menu_button.setObjectName("back_to_main_menu_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Мой словарь"))
        self.search_string_label.setText(_translate("Dialog", "Строка поиска"))
        self.add_word_button.setText(_translate("Dialog", "Добавить слово"))
        self.delete_word_button.setText(_translate("Dialog", "Удалить слово"))
        self.back_to_main_menu_button.setText(_translate("Dialog", "<-------"))
