# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultTrainigDialog_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 230)
        self.your_result_label = QtWidgets.QLabel(Dialog)
        self.your_result_label.setGeometry(QtCore.QRect(120, 20, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.your_result_label.setFont(font)
        self.your_result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.your_result_label.setObjectName("your_result_label")
        self.result_in_procents_label = QtWidgets.QLabel(Dialog)
        self.result_in_procents_label.setGeometry(QtCore.QRect(70, 110, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.result_in_procents_label.setFont(font)
        self.result_in_procents_label.setText("")
        self.result_in_procents_label.setObjectName("result_in_procents_label")
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setGeometry(QtCore.QRect(300, 190, 75, 23))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Окно вывода результата"))
        self.your_result_label.setText(_translate("Dialog", "Ваш Результат"))
        self.ok_button.setText(_translate("Dialog", "Ok"))
