# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainingDialog_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.next_word_btn = QtWidgets.QPushButton(Dialog)
        self.next_word_btn.setGeometry(QtCore.QRect(284, 160, 91, 23))
        self.next_word_btn.setObjectName("next_word_btn")
        self.back_to_main_menu_button = QtWidgets.QPushButton(Dialog)
        self.back_to_main_menu_button.setGeometry(QtCore.QRect(20, 160, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.back_to_main_menu_button.setFont(font)
        self.back_to_main_menu_button.setStyleSheet("")
        self.back_to_main_menu_button.setObjectName("back_to_main_menu_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Поставьте ударение в слове"))
        self.next_word_btn.setText(_translate("Dialog", "Следущее слово"))
        self.back_to_main_menu_button.setText(_translate("Dialog", "Выйти"))
